language: cpp
compiler:
  - gcc
  - clang
  
install:
  - df
  - sudo apt-get -y update
  - sudo apt-get -y install cmake libqt4-dev libuchardet-dev shntool xvfb python-software-properties
  - sudo add-apt-repository -y ppa:flacon
  - sudo apt-get -y update
  - sudo apt-get -y install flac mac vorbis-tools wavpack lame vorbisgain mp3gain ttaenc

script: 
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTS=Yes ..
  - make
  - xvfb-run tests/flacon_test
